export interface Article {
  slug: string;
  category: string;
  title: string;
  summary: string;
  excerpt: string;
  author: string;
  readTime: string;
  date: string;
  image: string | null;
  externalUrl: string;
}

export const featuredArticle: Article = {
  slug: 'the-curators-gambit',
  category: 'Strategy',
  title: "The Curator's Gambit: How Jeff Sprecher Built a Billion-Dollar Empire by Buying What Others Abandoned",
  summary: 'How Jeff Sprecher turned a $1,000 acquisition into one of world\'s largest exchange groups — and what platform builders can learn from curator approach.',
  excerpt: 'A masterclass in recognizing value others overlook, and building infrastructure that compounds over decades.',
  author: 'JP James',
  readTime: '32 min read',
  date: 'Jan 29, 2025',
  image: 'https://static.wixstatic.com/media/c54403_1179f9f19c6845438f229b36e316c1d8~mv2.jpeg/v1/fill/w_980,h_713,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/c54403_1179f9f19c6845438f229b36e316c1d8~mv2.jpeg',
  externalUrl: 'https://www.hiveresearch.com/post/the-curator-s-gambit-how-jeff-sprecher-built-a-billion-dollar-empire-by-buying-what-others-abandone',
};

export const allArticles: Article[] = [
  {
    slug: 'the-curators-gambit',
    category: 'Strategy',
    title: "The Curator's Gambit: How Jeff Sprecher Built a Billion-Dollar Empire by Buying What Others Abandoned",
    summary: 'How Jeff Sprecher turned a $1,000 acquisition into one of world\'s largest exchange groups — and what platform builders can learn from curator approach.',
    excerpt: 'A masterclass in recognizing value others overlook, and building infrastructure that compounds over decades.',
    author: 'JP James',
    readTime: '32 min read',
    date: 'Jan 29, 2025',
    image: 'https://static.wixstatic.com/media/c54403_0796113b24314e50a8a00afc8b6d935f~mv2.jpeg/v1/fill/w_978,h_704,al_c,q_85,enc_avif,quality_auto/c54403_0796113b24314e50a8a00afc8b6d935f~mv2.jpeg',
    externalUrl: 'https://www.hiveresearch.com/post/the-curator-s-gambit-how-jeff-sprecher-built-a-billion-dollar-empire-by-buying-what-others-abandone',
  },
  {
    slug: 'clark-dean-georgias-future',
    category: 'Strategy',
    title: "From Biomedical Engineering to Public Service: Clark Dean on Building Georgia's Future",
    summary: 'A conversation on leadership, data-driven decision making, and what it means to serve 11 million constituents with clarity and accountability.',
    excerpt: 'How analytical rigor combined with human connection shapes durable public and organizational outcomes.',
    author: 'JP James',
    readTime: '12 min read',
    date: 'Dec 30, 2024',
    image: 'https://static.wixstatic.com/media/c54403_4d840a7a507643c5b255e188ff5955d4~mv2.png/v1/fill/w_978,h_704,al_c,q_90,enc_avif,quality_auto/c54403_4d840a7a507643c5b255e188ff5955d4~mv2.png',
    externalUrl: 'https://www.hiveresearch.com/post/from-biomedical-engineering-to-publicservice-clark-dean-on-building-georgia-sfuture',
  },
  {
    slug: 'jamie-dimon-atlanta',
    category: 'Strategy',
    title: 'My Key Takeaways from Atlanta Conversation with Jamie Dimon',
    summary: 'JP James reflects on JPMorgan CEO Jamie Dimon\'s leadership philosophy — principled pragmatism, long-term value creation, and why ground-truth market engagement beats filtered reports.',
    excerpt: 'Effective leadership in volatile times demands getting out of headquarters and basing decisions on long-term value, not quarterly metrics.',
    author: 'JP James',
    readTime: '6 min read',
    date: 'Aug 10, 2025',
    image: 'https://static.wixstatic.com/media/c54403_4d840a7a507643c5b255e188ff5955d4~mv2.png/v1/fill/w_978,h_704,al_c,q_90,enc_avif,quality_auto/c54403_4d840a7a507643c5b255e188ff5955d4~mv2.png',
    externalUrl: 'https://www.hiveresearch.com/post/my-key-takeaways-from-the-atlanta-conversation-with-jamie-dimon',
  },
  {
    slug: 'peach-values-framework',
    category: 'Operations',
    title: 'THE PEACH VALUES FRAMEWORK: A Guide to Building High-Performance Culture Through Value-Driven Leadership',
    summary: 'How JP James\'s PEACH framework — Partnership, Execution, Aptitude, Communication, Humility — creates meritocratic organizations where diverse talent thrives.',
    excerpt: 'Sustainable competitive advantage comes from building cultures that prioritize character alignment over credentials.',
    author: 'JP James',
    readTime: '6 min read',
    date: 'Aug 5, 2025',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/the-peach-values-framework-a-guide-to-building-high-performance-culture-through-value-driven-leadership',
  },
  {
    slug: 'deep-work-day-framework',
    category: 'Operations',
    title: 'The Deep Work Day Framework',
    summary: 'A systematic approach to structuring your day for maximum productivity and deep work sessions.',
    excerpt: 'The most valuable work happens in deep work sessions — here\'s how to structure your day to maximize them.',
    author: 'Hive Research Institute',
    readTime: '8 min read',
    date: 'Jan 2025',
    image: 'https://static.wixstatic.com/media/67ef96_8b6d463cf62147ad8755afcf008db381~mv2.png/v1/fill/w_980,h_702,al_c,q_90,usm_0.66_1.00_0.01,enc_avif,quality_auto/67ef96_8b6d463cf62147ad8755afcf008db381~mv2.png',
    externalUrl: 'https://www.hiveresearch.com/post/the-deep-work-day-framework',
  },
  {
    slug: 'h1b-labor-market-signals',
    category: 'Operations',
    title: 'What H-1B Policy Changes Tell Us About Labor Market Signals',
    summary: 'Analyzing recent H-1B policy changes and what they reveal about broader labor market trends and implications for lending operations.',
    excerpt: 'Immigration policy changes are leading indicators of labor market shifts — and lenders need to pay attention.',
    author: 'Hive Research Institute',
    readTime: '8 min read',
    date: 'Jan 2025',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/what-h-1b-policy-changes-tell-us-about-labor-market-signals',
  },
  {
    slug: 'lenders-labor-market',
    category: 'Growth',
    title: "What lenders can learn from August's labor market signals",
    summary: 'A practical reading of labor market data through lens of lending operations — what employment trends mean for underwriting posture and portfolio risk.',
    excerpt: 'Labor market signals are underwriting signals. Most lenders read them too late.',
    author: 'Hive Research Institute',
    readTime: '7 min read',
    date: 'Sep 2024',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/what-lenders-can-learn-from-august-s-labor-market-signals',
  },
  {
    slug: 'middle-class-mirage',
    category: 'Growth',
    title: 'THE MIDDLE CLASS MIRAGE: A Guide to Understanding Modern Financial Fragility',
    summary: 'Why earning a middle-class salary no longer means financial security — and what to shift in consumer financial stability means for lending market opportunity.',
    excerpt: 'The addressable market for consumer lending is expanding precisely because financial fragility is growing.',
    author: 'Hive Research Institute',
    readTime: '8 min read',
    date: 'Oct 2024',
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/the-middle-class-mirage-a-guide-to-understanding-modern-financial-fragility',
  },
  {
    slug: 'china-deflationary-crisis',
    category: 'Growth',
    title: "The Hidden Depth of China's Deflationary Crisis: An Empirical Analysis",
    summary: 'An empirical analysis of China\'s deflationary pressures and downstream implications for global lending markets and capital flows.',
    excerpt: 'The deflationary signals coming out of China are structural, not cyclical — and implications for global credit markets are underappreciated.',
    author: 'Hive Research Institute',
    readTime: '10 min read',
    date: 'Oct 2024',
    image: 'https://static.wixstatic.com/media/c54403_b993de3f4903478fb43b26def3b8d3af~mv2.png/v1/fill/w_978,h_704,al_c,q_90,enc_avif,quality_auto/c54403_b993de3f4903478fb43b26def3b8d3af~mv2.png',
    externalUrl: 'https://www.hiveresearch.com/post/the-hidden-depth-of-china-s-deflationary-crisis-an-empirical-analysis',
  },
  {
    slug: 'quantum-ai-convergence',
    category: 'AI',
    title: 'The Quantum-AI Convergence: My Journey Through Complex Systems',
    summary: 'A first-person account of delivering an advanced technology masterclass at Georgia Tech on convergence of artificial intelligence, quantum computing, and complex adaptive systems.',
    excerpt: 'Standing before a Georgia Tech classroom, surrounded by semiconductor engineers and fintech experts, sharing a comprehensive framework for understanding technological revolution ahead.',
    author: 'JP James',
    readTime: '11 min read',
    date: 'Nov 3, 2025',
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/the-quantum-ai-convergence-my-journey-through-complex-systems',
  },
  {
    slug: 'rethinking-ai-agent-architecture',
    category: 'AI',
    title: 'Rethinking AI Agent Architecture: A Case Study in Code Execution Over Protocol Abstraction',
    summary: 'A case study examining why direct code execution outperforms protocol abstraction layers in production AI agent systems.',
    excerpt: 'The architectural decisions made early in AI agent design compound rapidly — and most teams are making the wrong ones.',
    author: 'Hive Research Institute',
    readTime: '19 min read',
    date: 'Nov 14, 2024',
    image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/rethinking-ai-agent-architecture-a-case-study-in-code-execution-over-protocol-abstraction',
  },
  {
    slug: 'ai-search-optimization',
    category: 'AI',
    title: 'AI SEARCH OPTIMIZATION: A Guide to Visibility in ChatGPT Era',
    summary: 'How businesses can adapt their content and digital presence to remain visible as AI-powered search replaces traditional search engine discovery.',
    excerpt: 'The rules of online visibility have changed. Most companies haven\'t updated their strategy.',
    author: 'Hive Research Institute',
    readTime: '9 min read',
    date: 'Oct 10, 2024',
    image: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/ai-search-optimization-a-guide-to-visibility-in-the-chatgpt-era',
  },
  {
    slug: 'private-credit-democratization',
    category: 'Growth',
    title: 'PRIVATE CREDIT DEMOCRATIZATION: A Guide to Navigating Wealth Management Revolution',
    summary: 'Transforming Financial Times\' Private Credit Market Analysis into Practical Leadership Applications - $48 billion in individual investor inflows are reshaping industry.',
    excerpt: 'Private credit funds are experiencing a historic shift as affluent individual investors pour capital into these vehicles, fundamentally altering an industry previously dominated by institutional capital.',
    author: 'Hive Research Institute',
    readTime: '9 min read',
    date: 'Sep 2, 2025',
    image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/private-credit-democratization-a-guide-to-navigating-the-wealth-management-revolution',
  },
  {
    slug: 'godfather-of-ai-warning',
    category: 'AI',
    title: "THE GODFATHER OF AI'S WARNING: A Guide to Strategic Leadership in Age of Artificial Intelligence - Geoffrey Hinton",
    summary: 'Transforming Geoffrey Hinton\'s AI Safety Insights into Practical Leadership Applications - Nobel Prize-winning AI pioneer warns of unprecedented existential risks.',
    excerpt: 'Nobel Prize-winning AI pioneer Geoffrey Hinton warns that artificial intelligence poses unprecedented existential risks to humanity while simultaneously creating massive economic opportunities.',
    author: 'Hive Research Institute',
    readTime: '8 min read',
    date: 'Aug 18, 2025',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/the-godfather-of-ai-s-warning-a-guide-to-strategic-leadership-in-the-age-of-artificial-intelligence',
  },
  {
    slug: 'fluid-intelligence',
    category: 'AI',
    title: 'FLUID INTELLIGENCE: A Guide to Next-Generation AI Capabilities',
    summary: 'Exploring next frontier of artificial intelligence capabilities and their implications for business strategy and competitive advantage.',
    excerpt: 'The evolution of AI from static problem-solving to dynamic, adaptive intelligence represents a fundamental shift in how we think about technological capability.',
    author: 'Hive Research Institute',
    readTime: '12 min read',
    date: 'Oct 15, 2025',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/fluid-intelligence-a-guide-to-next-generation-ai-capabilities',
  },
  {
    slug: 'life-design-mastery',
    category: 'Strategy',
    title: 'LIFE DESIGN MASTERY: A Guide to Strategic Personal and Professional Development',
    summary: 'A comprehensive framework for designing and executing strategic personal and professional development plans that align with long-term vision.',
    excerpt: 'Strategic life design requires the same rigor and discipline as business strategy - clear vision, systematic execution, and continuous adaptation.',
    author: 'Hive Research Institute',
    readTime: '10 min read',
    date: 'Sep 15, 2025',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/life-design-mastery-a-guide-to-strategic-personal-and-professional-development',
  },
  {
    slug: 'api-to-mcp-transformation',
    category: 'AI',
    title: 'API-TO-MCP TRANSFORMATION: A Leadership Guide to AI Integration Strategy',
    summary: 'A comprehensive guide for leaders on transforming traditional API architectures to Model Context Protocol (MCP) for AI integration.',
    excerpt: 'The shift from traditional APIs to MCP represents a fundamental architectural change that requires strategic leadership and systematic implementation.',
    author: 'Hive Research Institute',
    readTime: '14 min read',
    date: 'Sep 8, 2025',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/api-to-mcp-transformation-a-leadership-guide-to-ai-integration-strategy',
  },
  {
    slug: 'ai-coding-productivity',
    category: 'AI',
    title: 'AI CODING PRODUCTIVITY: A Guide to Strategic Implementation in Software Engineering',
    summary: 'A strategic guide for implementing AI-powered coding productivity tools in software engineering organizations.',
    excerpt: 'AI coding tools represent a fundamental shift in software development productivity, but successful implementation requires strategic planning and cultural change.',
    author: 'Hive Research Institute',
    readTime: '11 min read',
    date: 'Sep 22, 2025',
    image: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/ai-coding-productivity-a-guide-to-strategic-implementation-in-software-engineering',
  },
  {
    slug: 'economic-cycles',
    category: 'Growth',
    title: 'ECONOMIC CYCLES: A Guide to Strategic Capital Allocation and Risk Management',
    summary: 'A comprehensive framework for understanding economic cycles and optimizing strategic capital allocation and risk management.',
    excerpt: 'Economic cycles create both risks and opportunities - strategic leaders need frameworks to navigate volatility while maintaining long-term growth objectives.',
    author: 'Hive Research Institute',
    readTime: '16 min read',
    date: 'Sep 29, 2025',
    image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/economic-cycles-a-guide-to-strategic-capital-allocation-and-risk-management',
  },
  {
    slug: 'election-integrity',
    category: 'Strategy',
    title: 'ELECTION INTEGRITY AND DEMOCRATIC RESILIENCE: A Guide to Building Public Trust in Electoral Systems',
    summary: 'A strategic framework for building public trust and ensuring integrity in democratic electoral systems.',
    excerpt: 'Democratic resilience requires systematic approaches to election integrity that build public trust while ensuring security and accessibility.',
    author: 'Hive Research Institute',
    readTime: '13 min read',
    date: 'Oct 6, 2025',
    image: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800&q=80',
    externalUrl: 'https://www.hiveresearch.com/post/election-integrity-and-democratic-resilience-a-guide-to-building-public-trust-in-electoral-systems',
  },
];

export const latestArticles = allArticles.slice(0, 6);
